<?php
require_once '../global_mysql_connect.php';
require_once 'shell.php';
/** Error reporting */
error_reporting(E_ALL);
/** Include path **/
set_include_path(get_include_path() . PATH_SEPARATOR . '../class/');
/** PHPExcel */
include 'PHPExcel.php';
// uncomment   
require_once 'PHPExcel/Writer/Excel5.php';    // 用于其他低版本xls   
// or   
//require_once 'PHPExcel/Writer/Excel2007.php'; // 用于 excel-2007 格式

// Create new PHPExcel object
$objExcel = new PHPExcel();
// 创建文件格式写入对象实例, uncomment   
$objWriter = new PHPExcel_Writer_Excel5($objExcel);    // 用于其他版本格式   
// or   
//$objWriter = new PHPExcel_Writer_Excel2007($objExcel); // 用于 2007 格式   
//$objWriter->setOffice2003Compatibility(true);   

//设置文档基本属性   
$objProps = $objExcel->getProperties();   
$objProps->setCreator("jtl");   
$objProps->setLastModifiedBy("Zeal Li");   
$objProps->setTitle("Office XLS Test Document");   
$objProps->setSubject("Office XLS Test Document, Demo");   
$objProps->setDescription("Test document, generated by PHPExcel.");   
$objProps->setKeywords("office excel PHPExcel");   
$objProps->setCategory("jtl");  

//设置当前的sheet索引，用于后续的内容操作。   
//一般只有在使用多个sheet的时候才需要显示调用。   
//缺省情况下，PHPExcel会自动创建第一个sheet被设置SheetIndex=0   
$objExcel->setActiveSheetIndex(0);
$objActSheet = $objExcel->getActiveSheet();
$objActSheet->setTitle('模具加工费用'.date('Y-m-j')."-BY_JTL"); 
$objExcel->getActiveSheet()->getDefaultRowDimension()->setRowHeight(25);
$objExcel->getActiveSheet()->getStyle('A1:I1')->getAlignment()->setWrapText(true);
 
//由PHPExcel根据传入内容自动判断单元格内容类型   
$objActSheet->setCellValue('A1', '序号');
$objActSheet->setCellValue('B1', '代码');
$objActSheet->setCellValue('C1', '项目名称');
$objActSheet->setCellValue('D1', '模具编号');
$objActSheet->setCellValue('E1', '目前状态');
$objActSheet->setCellValue('F1', '外协费用');
$objActSheet->setCellValue('G1', '烧焊费用');
$objActSheet->setCellValue('H1', '试模费用');
$objActSheet->setCellValue('I1', '费用总计');

$sql = $_SESSION['mould_processing']." ORDER BY `db_mould`.`mould_number` ASC,`db_mould`.`mouldid` ASC";
$result = $db->query($sql);
$result_allid = $db->query($sql);
if($result->num_rows){
	$array_all_mouldid = '';
	while($row_allid = $result_allid->fetch_assoc()){
		$array_all_mouldid .= $row_allid['mouldid'].',';
	}
	$array_all_mouldid = rtrim($array_all_mouldid,',');
	//统计烧焊费用
	$sql_weld = "SELECT `mouldid`,SUM(`cost`) AS `total_cost` FROM `db_mould_weld` WHERE `mouldid` IN ($array_all_mouldid) AND `weld_status` = 1 GROUP BY `mouldid`";
	$result_weld = $db->query($sql_weld);
	if($result_weld->num_rows){
		while($row_weld = $result_weld->fetch_assoc()){
			$array_weld[$row_weld['mouldid']] = $row_weld['total_cost'];
		}
	}else{
		$array_weld = array();
	}
	//统计外发费用
	$sql_outward = "SELECT `mouldid`,SUM(`cost`) AS `total_cost` FROM `db_mould_outward` WHERE `mouldid` IN ($array_all_mouldid) AND `outward_status` = 1 GROUP BY `mouldid`";
	$result_outward = $db->query($sql_outward);
	if($result_outward->num_rows){
		while($row_outward = $result_outward->fetch_assoc()){
			$array_outward[$row_outward['mouldid']] = $row_outward['total_cost'];
		}
	}else{
		$array_outward = array();
	}
	//统计试模费用
	$sql_try = "SELECT `mouldid`,SUM(`cost`) AS `total_cost` FROM `db_mould_try` WHERE `mouldid` IN ($array_all_mouldid) AND `try_status` = 1 GROUP BY `mouldid`";
	$result_try = $db->query($sql_try);
	if($result_try->num_rows){
		while($row_try = $result_try->fetch_assoc()){
			$array_try[$row_try ['mouldid']] = $row_try ['total_cost'];
		}
	}else{
		$array_try = array();
	}
	$i = 2;
	while($row = $result->fetch_assoc()){
		$mouldid = $row['mouldid'];
		$outward_cost = array_key_exists($mouldid,$array_outward)?$array_outward[$mouldid]:0;
		$weld_cost = array_key_exists($mouldid,$array_weld)?$array_weld[$mouldid]:0;
		$try_cost = array_key_exists($mouldid,$array_try)?$array_try[$mouldid]:0;
		$total_cost = $weld_cost + $outward_cost + $try_cost;
		$objActSheet->setCellValue('A'.$i, $i-1);
		$objActSheet->setCellValue('B'.$i, $row['client_code']);
		$objActSheet->setCellValue('C'.$i, $row['project_name']);
		$objActSheet->setCellValue('D'.$i, $row['mould_number']);
		$objActSheet->setCellValue('E'.$i, $row['mould_statusname']);
		$objActSheet->setCellValue('F'.$i, $outward_cost);
		$objActSheet->setCellValue('G'.$i, $weld_cost);
		$objActSheet->setCellValue('H'.$i, $try_cost);
		$objActSheet->setCellValue('I'.$i, $total_cost);
		$i++;
	}
	$objExcel->getActiveSheet()->mergeCells('A'.$i.':E'.$i.'');
	$objActSheet->setCellValue('A'.$i, 'Total');
	$objActSheet->setCellValue('F'.$i, '=SUM(F2:F'.($i-1).')');
	$objActSheet->setCellValue('G'.$i, '=SUM(G2:G'.($i-1).')');
	$objActSheet->setCellValue('H'.$i, '=SUM(H2:H'.($i-1).')');
	$objActSheet->setCellValue('I'.$i, '=SUM(I2:I'.($i-1).')');

//格式
$objActSheet->getStyle('A1:I'.($i))->getBorders()->getAllBorders()->setBorderStyle(PHPExcel_Style_Border::BORDER_THIN); //设置单元格为实线
$objActSheet->getStyle('A1:I'.($i))->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);  //水平居中
$objActSheet->getStyle('A1:I'.($i))->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);// 竖直居中
		
//设置宽度
$objActSheet->getColumnDimension('A')->setWidth(5);  
$objActSheet->getColumnDimension('B')->setWidth(12);
$objActSheet->getColumnDimension('C')->setWidth(12);
$objActSheet->getColumnDimension('D')->setWidth(12);
$objActSheet->getColumnDimension('E')->setWidth(12);

//设置字体   
$objStyle2 = $objActSheet->getStyle('A1:I1'); 
$objFont2 = $objStyle2->getFont();   
$objFont2->setName('微软雅黑','宋体');   
$objFont2->setSize(10);
$objFont2->setBold(true);   
$objFont2->getColor()->setARGB('FF000000'); 
//设置字体   
$objStyle1 = $objActSheet->getStyle('A2:I'.($i)); 
$objFont1 = $objStyle1->getFont();   
$objFont1->setName('微软雅黑','宋体');   
$objFont1->setSize(10);   
$objFont1->setBold(false);   
$objFont1->getColor()->setARGB('FF000000'); 

//输出内容   
//$m_strOutputPath = "../upload/tmp/"; 
$m_strOutputExcelFileName = '模具加工费用_'.date('Y-m-j_H_i_s').".xls";
//输到文件   
//$objWriter->save($m_strOutputPath . $m_strOutputExcelFileName);

//到浏览器
header("Content-Type: application/force-download");   
header("Content-Type: application/octet-stream");   
header("Content-Type: application/download");   
header('Content-Disposition:inline;filename="'.$m_strOutputExcelFileName.'"');   
header("Content-Transfer-Encoding: binary");   
header("Expires: Mon, 26 Jul 1997 05:00:00 GMT");   
header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");   
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");   
header("Pragma: no-cache");   
$objWriter->save('php://output');
}else{
	echo "No data!";
}
?>