<?php
require_once '../global_mysql_connect.php';
require_once 'shell.php';
/** Error reporting */
error_reporting(E_ALL);
/** Include path **/
set_include_path(get_include_path() . PATH_SEPARATOR . '../class/');
/** PHPExcel */
include 'PHPExcel.php';
// uncomment   
require_once 'PHPExcel/Writer/Excel5.php';    // 用于其他低版本xls   
// or   
//require_once 'PHPExcel/Writer/Excel2007.php'; // 用于 excel-2007 格式

// Create new PHPExcel object
$objExcel = new PHPExcel();
// 创建文件格式写入对象实例, uncomment   
$objWriter = new PHPExcel_Writer_Excel5($objExcel);    // 用于其他版本格式   
// or   
//$objWriter = new PHPExcel_Writer_Excel2007($objExcel); // 用于 2007 格式   
//$objWriter->setOffice2003Compatibility(true);   

//设置文档基本属性   
$objProps = $objExcel->getProperties();   
$objProps->setCreator("jtl");   
$objProps->setLastModifiedBy("Zeal Li");   
$objProps->setTitle("Office XLS Test Document");   
$objProps->setSubject("Office XLS Test Document, Demo");   
$objProps->setDescription("Test document, generated by PHPExcel.");   
$objProps->setKeywords("office excel PHPExcel");   
$objProps->setCategory("jtl");  

//设置当前的sheet索引，用于后续的内容操作。   
//一般只有在使用多个sheet的时候才需要显示调用。   
//缺省情况下，PHPExcel会自动创建第一个sheet被设置SheetIndex=0   
$objExcel->setActiveSheetIndex(0);
$objActSheet = $objExcel->getActiveSheet();
$objActSheet->setTitle('员工'.date('Y-m-j')."-BY_JTL"); 
$objExcel->getActiveSheet()->getDefaultRowDimension()->setRowHeight(25);
$objExcel->getActiveSheet()->getStyle('A1:T1')->getAlignment()->setWrapText(true);
 
//由PHPExcel根据传入内容自动判断单元格内容类型   
$objActSheet->setCellValue('A1', '序号');
$objActSheet->setCellValue('B1', '工号');
$objActSheet->setCellValue('C1', '员工');
$objActSheet->setCellValue('D1', '部门');
$objActSheet->setCellValue('E1', '职务');
$objActSheet->setCellValue('F1', '岗位级别');
$objActSheet->setCellValue('G1', '上级领导');
$objActSheet->setCellValue('H1', '文化程序');
$objActSheet->setCellValue('I1', '身份证号码');
$objActSheet->setCellValue('J1', '出生年月');
$objActSheet->setCellValue('K1', '年龄');
$objActSheet->setCellValue('L1', '性别');
$objActSheet->setCellValue('M1', '籍贯');
$objActSheet->setCellValue('N1', '入职日期');
$objActSheet->setCellValue('O1', '离职日期');
$objActSheet->setCellValue('P1', '工龄');
$objActSheet->setCellValue('Q1', '联系电话');
$objActSheet->setCellValue('R1', '家庭地址');
$objActSheet->setCellValue('S1', 'EMail');
$objActSheet->setCellValue('T1', '状态');

$sql_employee = $_SESSION['employee'];
$result_employee = $db->query($sql_employee);
if($result_employee->num_rows){
	$array_employeid = '';
	while($row_id = $result_employee->fetch_assoc()){
		$array_employeid .= $row_id['employeeid'].',';
	}
	$array_employeid = rtrim($array_employeid,',');
	$sql = "SELECT `db_employee`.`employee_name`,`db_employee`.`employee_number`,`db_employee`.`employee_number`,`db_employee`.`position_type`,`db_employee`.`education`,`db_employee`.`idcard`,`db_employee`.`birthday`,`db_employee`.`sex`,`db_employee`.`nativeplace`,`db_employee`.`entrydate`,`db_employee`.`termdate`,`db_employee`.`phone`,`db_employee`.`address`,`db_employee`.`email`,`db_employee`.`employee_status`,`db_department`.`dept_name`,`db_personnel_position`.`position_name`,(DATE_FORMAT(CURDATE(),'%Y')-DATE_FORMAT(`db_employee`.`birthday`,'%Y')) AS `age`,IF((`db_employee`.`employee_status` = 1),ROUND(DATEDIFF(CURDATE(),`db_employee`.`entrydate`)/365,1),ROUND(DATEDIFF(`db_employee`.`termdate`,`db_employee`.`entrydate`)/365,1)) AS `work_year`,`db_superior`.`employee_name` AS `superior_name` FROM `db_employee` INNER JOIN `db_employee` AS `db_superior` ON `db_superior`.`employeeid` = `db_employee`.`superior` INNER JOIN `db_department` ON `db_department`.`deptid` = `db_employee`.`deptid` INNER JOIN `db_personnel_position` ON `db_personnel_position`.`positionid` = `db_employee`.`positionid` WHERE `db_employee`.`employeeid` IN ($array_employeid) ORDER BY `db_department`.`dept_order` ASC,`db_employee`.`employee_number` ASC,`db_employee`.`employeeid` ASC";
	$result = $db->query($sql);
	$i = 2;
	while($row = $result->fetch_assoc()){
		$employee_status = $row['employee_status'];
		$postition_type = array_key_exists($row['position_type'],$array_position_type)?$array_position_type[$row['position_type']]:'--';
		$education = array_key_exists($row['education'],$array_education_type)?$array_education_type[$row['education']]:'--';
		$termdate = $employee_status?'--':$row['termdate'];
		$objActSheet->setCellValue('A'.$i, $i-1);
		$objActSheet->setCellValue('B'.$i, $row['employee_number']);
		$objActSheet->setCellValue('C'.$i, $row['employee_name']);
		$objActSheet->setCellValue('D'.$i, $row['dept_name']);
		$objActSheet->setCellValue('E'.$i, $row['position_name']);
		$objActSheet->setCellValue('F'.$i, $postition_type);
		$objActSheet->setCellValue('G'.$i, $row['superior_name']);
		$objActSheet->setCellValue('H'.$i, $education);
		$objExcel->getActiveSheet()->setCellValueExplicit('I'.$i,$row['idcard'],PHPExcel_Cell_DataType::TYPE_STRING);
		$objActSheet->setCellValue('J'.$i, $row['birthday']);
		$objActSheet->setCellValue('K'.$i, $row['age']);
		$objActSheet->setCellValue('L'.$i, $row['sex']);
		$objActSheet->setCellValue('M'.$i, $row['nativeplace']);
		$objActSheet->setCellValue('N'.$i, $row['entrydate']);
		$objActSheet->setCellValue('O'.$i, $termdate);
		$objActSheet->setCellValue('P'.$i, $row['work_year']);
		$objActSheet->setCellValue('Q'.$i, $row['phone']);
		$objActSheet->setCellValue('R'.$i, $row['address']);
		$objActSheet->setCellValue('S'.$i, $row['email']);
		$objActSheet->setCellValue('T'.$i, $array_employee_status[$row['employee_status']]);
		$i++;
	}

//格式
$objActSheet->getStyle('A1:T'.($i-1))->getBorders()->getAllBorders()->setBorderStyle(PHPExcel_Style_Border::BORDER_THIN); //设置单元格为实线
$objActSheet->getStyle('A1:T'.($i-1))->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);  //水平居中
$objActSheet->getStyle('A1:T'.($i-1))->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);// 竖直居中

		
//设置宽度
$objActSheet->getColumnDimension('A')->setWidth(5);  
$objActSheet->getColumnDimension('B')->setWidth(12);
$objActSheet->getColumnDimension('C')->setWidth(12);
$objActSheet->getColumnDimension('D')->setWidth(15);
$objActSheet->getColumnDimension('E')->setWidth(15);
$objActSheet->getColumnDimension('F')->setWidth(12);
$objActSheet->getColumnDimension('G')->setWidth(12);
$objActSheet->getColumnDimension('I')->setWidth(30);
$objActSheet->getColumnDimension('J')->setWidth(12);
$objActSheet->getColumnDimension('M')->setWidth(25);
$objActSheet->getColumnDimension('N')->setWidth(12);
$objActSheet->getColumnDimension('O')->setWidth(12);
$objActSheet->getColumnDimension('Q')->setWidth(15);
$objActSheet->getColumnDimension('R')->setWidth(35);
$objActSheet->getColumnDimension('S')->setWidth(30);

//设置字体   
$objStyle2 = $objActSheet->getStyle('A1:T1'); 
$objFont2 = $objStyle2->getFont();   
$objFont2->setName('微软雅黑','宋体');   
$objFont2->setSize(10);
$objFont2->setBold(true);   
$objFont2->getColor()->setARGB('FF000000'); 
//设置字体   
$objStyle1 = $objActSheet->getStyle('A2:T'.($i-1)); 
$objFont1 = $objStyle1->getFont();   
$objFont1->setName('微软雅黑','宋体');   
$objFont1->setSize(10);   
$objFont1->setBold(false);   
$objFont1->getColor()->setARGB('FF000000'); 

//输出内容   
$m_strOutputPath = "../upload/tmp/"; 
$m_strOutputExcelFileName = '员工_'.date('Y-m-j_H_i_s').".xls";
//输到文件   
//$objWriter->save($m_strOutputPath . $m_strOutputExcelFileName); 

//到浏览器

header("Content-Type: application/force-download");   
header("Content-Type: application/octet-stream");   
header("Content-Type: application/download");   
header('Content-Disposition:inline;filename="'.$m_strOutputExcelFileName.'"');   
header("Content-Transfer-Encoding: binary");   
header("Expires: Mon, 26 Jul 1997 05:00:00 GMT");   
header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");   
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");   
header("Pragma: no-cache");   
$objWriter->save('php://output');
}else{
	echo "No data!";
}
?>