<?php
require_once '../global_mysql_connect.php';
require_once 'shell.php';
/** Error reporting */
error_reporting(E_ALL);
/** Include path **/
set_include_path(get_include_path() . PATH_SEPARATOR . '../class/');
/** PHPExcel */
include 'PHPExcel.php';
// uncomment   
require_once 'PHPExcel/Writer/Excel5.php';    // 用于其他低版本xls   
// or   
//require_once 'PHPExcel/Writer/Excel2007.php'; // 用于 excel-2007 格式

// Create new PHPExcel object
$objExcel = new PHPExcel();
// 创建文件格式写入对象实例, uncomment   
$objWriter = new PHPExcel_Writer_Excel5($objExcel);    // 用于其他版本格式   
// or   
//$objWriter = new PHPExcel_Writer_Excel2007($objExcel); // 用于 2007 格式   
//$objWriter->setOffice2003Compatibility(true);   

//设置文档基本属性   
$objProps = $objExcel->getProperties();   
$objProps->setCreator("jtl");   
$objProps->setLastModifiedBy("Zeal Li");   
$objProps->setTitle("Office XLS Test Document");   
$objProps->setSubject("Office XLS Test Document, Demo");   
$objProps->setDescription("Test document, generated by PHPExcel.");   
$objProps->setKeywords("office excel PHPExcel");   
$objProps->setCategory("jtl");  

//设置当前的sheet索引，用于后续的内容操作。   
//一般只有在使用多个sheet的时候才需要显示调用。   
//缺省情况下，PHPExcel会自动创建第一个sheet被设置SheetIndex=0   
$objExcel->setActiveSheetIndex(0);
$objActSheet = $objExcel->getActiveSheet();
$objActSheet->setTitle('刀具申购明细'.date('Y-m-j')."-BY_JTL"); 
$objExcel->getActiveSheet()->getDefaultRowDimension()->setRowHeight(25);
$objExcel->getActiveSheet()->getStyle('A1:O1')->getAlignment()->setWrapText(true);
 
//由PHPExcel根据传入内容自动判断单元格内容类型   
$objActSheet->setCellValue('A1', '序号');
$objActSheet->setCellValue('B1', '申购单号');
$objActSheet->setCellValue('C1', '类型');
$objActSheet->setCellValue('D1', '规格');
$objActSheet->setCellValue('E1', '材质');
$objActSheet->setCellValue('F1', '硬度');
$objActSheet->setCellValue('G1', '品牌');
$objActSheet->setCellValue('H1', '供应商');
$objActSheet->setCellValue('I1', '申购数量');
$objActSheet->setCellValue('J1', '入库数量');
$objActSheet->setCellValue('K1', '单位');
$objActSheet->setCellValue('L1', '申购人');
$objActSheet->setCellValue('M1', '申购日期');
$objActSheet->setCellValue('N1', '计划回厂日期');
$objActSheet->setCellValue('O1', '状态');

$sql = $_SESSION['purchase_list']." ORDER BY `db_cutter_purchase`.`purchaseid` DESC,`db_cutter_purchase_list`.`purchase_listid` DESC";
$result = $db->query($sql);
if($result->num_rows){
	$i = 2;
	while($row = $result->fetch_assoc()){
		$listid = $row['listid'];
		$cutter_order_status = ($listid)?'已下单':'未下单';
		$in_quantity = ($listid)?$row['in_quantity']:0;
		$objActSheet->setCellValue('A'.$i, $i-1);
		$objActSheet->setCellValue('B'.$i, $row['purchase_number']);
		$objActSheet->setCellValue('C'.$i, $row['type']);
		$objActSheet->setCellValue('D'.$i, $row['specification']);
		$objActSheet->setCellValue('E'.$i, $array_cutter_texture[$row['texture']]);
		$objActSheet->setCellValue('F'.$i, $row['hardness']);
		$objActSheet->setCellValue('G'.$i, $row['brand']);
		$objActSheet->setCellValue('H'.$i, $row['supplier_cname']);
		$objActSheet->setCellValue('I'.$i, $row['quantity']);
		$objActSheet->setCellValue('J'.$i, $in_quantity);
		$objActSheet->setCellValue('K'.$i, '件');
		$objActSheet->setCellValue('L'.$i, $row['employee_name']);
		$objActSheet->setCellValue('M'.$i, $row['purchase_date']);
		$objActSheet->setCellValue('N'.$i, $row['plan_date']);
		$objActSheet->setCellValue('O'.$i, $cutter_order_status);
		$i++;
	}

//格式
$objActSheet->getStyle('A1:O'.($i-1))->getBorders()->getAllBorders()->setBorderStyle(PHPExcel_Style_Border::BORDER_THIN); //设置单元格为实线
$objActSheet->getStyle('A1:O'.($i-1))->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);  //水平居中
$objActSheet->getStyle('A1:O'.($i-1))->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);// 竖直居中
		
//设置宽度
$objActSheet->getColumnDimension('A')->setWidth(8);  
$objActSheet->getColumnDimension('B')->setWidth(15);
$objActSheet->getColumnDimension('C')->setWidth(12);
$objActSheet->getColumnDimension('D')->setWidth(20);
$objActSheet->getColumnDimension('E')->setWidth(12);
$objActSheet->getColumnDimension('F')->setWidth(20);
$objActSheet->getColumnDimension('G')->setWidth(12);
$objActSheet->getColumnDimension('H')->setWidth(12);
$objActSheet->getColumnDimension('M')->setWidth(15);
$objActSheet->getColumnDimension('N')->setWidth(15);
$objActSheet->getColumnDimension('O')->setWidth(15);

//设置字体   
$objStyle2 = $objActSheet->getStyle('A1:N1'); 
$objFont2 = $objStyle2->getFont();   
$objFont2->setName('微软雅黑','宋体');   
$objFont2->setSize(10);
$objFont2->setBold(true);   
$objFont2->getColor()->setARGB('FF000000'); 
//设置字体   
$objStyle1 = $objActSheet->getStyle('A2:N'.($i)); 
$objFont1 = $objStyle1->getFont();   
$objFont1->setName('微软雅黑','宋体');   
$objFont1->setSize(10);   
$objFont1->setBold(false);   
$objFont1->getColor()->setARGB('FF000000'); 

//输出内容   
//$m_strOutputPath = "../upload/tmp/"; 
$m_strOutputExcelFileName = '刀具申购明细_'.date('Y-m-j_H_i_s').".xls";
//输到文件   
//$objWriter->save($m_strOutputPath . $m_strOutputExcelFileName);

//到浏览器
header("Content-Type: application/force-download");   
header("Content-Type: application/octet-stream");   
header("Content-Type: application/download");   
header('Content-Disposition:inline;filename="'.$m_strOutputExcelFileName.'"');   
header("Content-Transfer-Encoding: binary");   
header("Expires: Mon, 26 Jul 1997 05:00:00 GMT");   
header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");   
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");   
header("Pragma: no-cache");   
$objWriter->save('php://output');
}else{
	echo "No data!";
}
?>